remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: Miguel Angel Roldan Cardona
submodulo: Lógica de Programación
periodo: 2023-2
url_foto: https://firebasestorage.googleapis.com/v0/b/proyectos-mr.appspot.com/o/WhatsApp%20Image%202023-09-15%20at%205.24.47%20PM%20(1).jpeg?alt=media&token=a221a563-8fe4-469f-98f4-33bfc11ded5e&_gl=1*i1lgph*_ga*MTExMzMzNDcwMS4xNjk0NTY3MDU2*_ga_CW55HF8NVT*MTY5NTg1MzI0MC42LjEuMTY5NTg1NTA4My4zNi4wLjA.

